import type { Metadata } from "next";
import type { ReactNode } from "react";
import { SiteFooter, SiteHeader } from "@/components/site";

export const metadata: Metadata = { title: "Philosophy" };

function EssaySection({ id, title, children }: { id: string; title: string; children: ReactNode }) {
  return (
    <section className="content-section shell philosophy-opening" aria-labelledby={id}>
      <div className="content-label">{id.replace("part-", "")}</div>
      <div className="prose-large">
        <h2 id={id}>{title}</h2>
        {children}
      </div>
    </section>
  );
}

export default function PhilosophyPage() {
  return (
    <>
      <SiteHeader />
      <main>
        <section className="page-intro shell">
          <p className="eyebrow">Philosophy</p>
          <h1>The Theory of Discipline</h1>
          <p>
            My philosophical work concerns truth, novelty, and the forms of thought through which a consistency that did not previously exist can be composed.
          </p>
        </section>

        <EssaySection id="part-I" title="How Is the New Possible?">
          <p>Looking back, I have come to think that one question has accompanied much of my philosophical work, long before I formulated it explicitly: <em>how is the new possible?</em> By the new I do not mean change as such. Things change continuously. Nor do I mean innovation, difference, or the rearrangement of possibilities already available within a given situation. My concern is with what I call <em>radical novelty</em>: the coming into existence of a consistency that cannot be derived from the existing resources of the situation in which it emerges. In what follows, when I speak simply of <em>novelty</em>, I mean radical novelty in this sense.</p>
          <p>I did not begin my philosophical work by formulating the problem in these terms. But retrospectively it helps me understand some of my earliest philosophical attractions. It was part of what drew me, in very different ways, to Hegel and Marx, to the later Kant, to Heidegger, and to Islamic mysticism. What interested me in these otherwise profoundly different forms of thought was the refusal to allow the given to determine completely the limits of what is possible. The same concern informed my interest in a conception of the subject whose fate remains open: a subject that is conditioned, divided and confronted by obstacles, but whose possibilities cannot be decided in advance by those conditions.</p>
          <p>I became unexpectedly conscious of the persistence of this question shortly after defending my doctoral dissertation in Prague in the spring of 2018. I travelled to Iran, where Dr. Elahi invited me to speak about my dissertation to a gathering of his students. I had to explain, in Persian and without much of the technical apparatus of my research, what the work was really about. I began with a question I had never used to describe the dissertation before: <em>How is the new possible?</em></p>
          <blockquote lang="fa" dir="rtl">کهنه کجا می‌رود نو ز کجا می‌رسد<br />گر نه ورای نظر عالم بی‌منتهاست</blockquote>
          <p><em>Where does the old go, and from where does the new arrive,<br />if beyond our sight there is not a world without end?</em></p>
          <p>What stayed with me afterward was not that the dissertation had explicitly been about novelty—it had not—but that, when its technical language had to be put aside, this was the question through which I instinctively chose to explain what was at stake.</p>
          <p>The question of novelty is inseparable, for me, from the question of <em>truth</em>. If everything that can appear is already determined by the structures, languages, relations or possibilities of an existing world, then novelty becomes impossible to think. What appears as new can amount only to a recombination of possibilities that the world already contains. To think novelty requires us to ask whether something can be produced within a situation that cannot be derived from the resources through which that situation presently organizes what is possible.</p>
          <p>This does not mean that novelty arrives from outside history. Every encounter from which novelty can emerge is situated. Thought itself is situated: it has a history, works with determinate resources, and encounters limits that are specific to the consistency it has acquired. What can constitute an impasse at one historical moment need not constitute an impasse at another. Novelty is therefore possible only within the determinate conditions of a situated thought.</p>
          <p>But historical determination does not imply historical sufficiency. The materialist premise underlying my work is that <em>being exceeds thinking</em>. No historically situated consistency of thought exhausts the being of what it encounters. This excess is not itself a historical occurrence, but an encounter with it always is. It occurs from within the particular resources and limits of a situated thought. History therefore conditions the encounter without determining in advance all the consequences that can be composed from it.</p>
          <p>Novelty, in this sense, comes neither from outside history nor simply from possibilities that history has already made available. It becomes possible when situated thought encounters what its existing resources cannot capture and succeeds in composing the consequences of that encounter.</p>
          <p>It was in Alain Badiou that I encountered the most sustained contemporary attempt to think this possibility. Badiou brought together elements that had previously appeared to me separately: a philosophy without transcendence; an axiomatic conception of thought; infinity understood mathematically rather than as an inaccessible beyond; and, crucially, an account in which an impasse or inconsistency need not simply mark the failure of thought but can become the site from which another consistency can be composed.</p>
          <p>My encounter with Badiou therefore did more than provide a new philosophical vocabulary for an old concern. It provided the terrain upon which the question <em>how is the new possible?</em> could begin to acquire a rigorous form. It was through studying that terrain closely that I eventually arrived at what I call the <em>Theory of Discipline</em>.</p>
        </EssaySection>

        <EssaySection id="part-II" title="Badiou and the Discovery of Discipline">
          <p>What initially drew me to Badiou was therefore not simply his theory of the event or his conception of the subject. It was the peculiar conjunction that made those concepts possible. Here was a philosophy committed to radical novelty without appealing to transcendence; one that took mathematics seriously as ontology, treated infinity as an immanent determination of being, and regarded the limits and impasses of a situation not merely as prohibitions but as possible conditions for the emergence of something new. The subject, in turn, was not given in advance. It came into existence through the work of sustaining the consequences of such an emergence.</p>
          <p>My doctoral research began from a more specific problem: Badiou’s theory of subjectivity and its relation to mathematical infinity. But as I followed his work across different periods, I became increasingly interested in something that seemed to persist beneath substantial changes in his philosophical vocabulary and mathematical resources. Badiou’s primary interest in logic and formal systems in the 1960s changed to a focus on political militancy and the theory of the subject in the 1970s, and to mathematics and ontology in the 1980s. Yet beneath these changes I began to recognize a recurrent way of proceeding.</p>
          <p>One of the earliest places where I became conscious of this was Badiou’s criticism of Jacques-Alain Miller’s use of Frege and number theory in his theory of suture. Miller had attempted to establish a conceptual priority of the Lacanian subject over Frege’s construction of number. Badiou objected not only to particular claims in the argument but to the operation being performed: mathematical concepts had been extracted from the conditions under which they possessed their consistency and made to perform philosophical and psychoanalytic work that those conditions did not warrant.</p>
          <p>What interested me was the principle implicit in the criticism. A form of thought establishes its own interior: its beginnings, objects, operations and criteria of consistency. Concepts acquire their force within such an interior. Crossing from one field into another is certainly possible—indeed, Badiou’s own philosophy continually moves between mathematics and philosophy—but such movement cannot be an arbitrary transfer of concepts. Something has to govern the legitimacy of the passage and the consequences that can be drawn from it. What struck me, even in this early encounter, was the dominance of an ontological orientation in his critique of how different disciplines of thinking must be treated.</p>
          <p>Once I began looking from this perspective, the same logic appeared elsewhere in Badiou’s work. A thought begins by accepting certain conditions. It constructs an interior and maintains its consistency. It follows the consequences made possible by that beginning. But it also encounters points at which its established resources cease to be sufficient. What matters then is not simply the existence of the limit or impasse, but what thought <em>does</em> there: whether it closes itself against what it cannot accommodate, collapses into inconsistency, or finds a way to extend itself and construct consequences that were not previously available to it.</p>
          <p>I came to use the word <em>discipline</em> for this recurrent logic. The term made sense to me because what Miller attempted to establish was a unified theory of discourse, and the logic according to which Badiou critiqued this theory involved an embedded practice within a particular discipline of thinking, where fidelity and formalism played instrumental roles.</p>
          <p>Initially, the concept helped me make sense of Badiou’s philosophical trajectory. What could appear as successive changes of direction began to look different when viewed through discipline. The mathematical and philosophical apparatus changed, sometimes profoundly, but a certain logic of construction persisted: beginning, interiority and consistency on one side; confrontation with limits, extension and the production of new consequences on the other.</p>
          <p>This also helped me understand why mathematics occupies such an unusual place in Badiou’s philosophy. Mathematics was not important merely because Badiou had made the controversial declaration that mathematics is ontology. Mathematical thinking offered an exceptionally rigorous instance of a thought that proceeds from decided beginnings, constructs consequences immanently, and repeatedly encounters limits that can themselves become occasions for further construction. Its history demonstrates that rigor and novelty are not opposites. On the contrary, some of the most radical transformations of thought become possible precisely because the requirements of consistency are taken seriously.</p>
          <p>But gradually I began to suspect that I had encountered something more than a useful way of interpreting Badiou. If the same logic could illuminate his changing accounts of ontology, truth and subjectivity; if it could help explain his use of mathematics as well as his insistence upon novelty; and if its operations could be identified beyond the particular philosophical vocabulary in which Badiou expressed them, then perhaps <em>discipline</em> was not simply something in Badiou that had gone unnamed.</p>
          <p>Perhaps it named a logic of thought in its own right.</p>
          <p>That possibility changed the direction of the project. The question was no longer only whether discipline could explain an underlying continuity in Badiou’s philosophy. The question became: <em>what is a discipline, what are its operations, and why is this particular form of thinking capable of producing truths and, with them, the possibility of novelty?</em></p>
          <p>Those questions mark the beginning of the Theory of Discipline.</p>
        </EssaySection>

        <EssaySection id="part-III" title="What Is the Theory of Discipline?">
          <p>A discipline, as I use the term, is not primarily an academic field, an institution, or an established body of knowledge. Nor is it defined by the people who practice it. A discipline is a <em>form of composition</em>: a structured process through which a consistency that did not previously exist can be produced.</p>
          <p>This is why the concept of discipline is inseparable from the problem of novelty. If novelty means more than variation within what is already possible, we have to explain how a consistency can be composed that is not derivable from the existing resources of the discipline. The problem is to understand how such a composition can take place <em>immanently</em>.</p>
          <p>A discipline begins. Every composition requires a beginning, and a beginning necessarily introduces a distinction. Certain elements, relations and operations acquire a place within the developing composition; others do not. In this sense a discipline establishes an <em>interior</em>. Interiority does not mean isolation from a world outside it. It means that a discipline develops its own criteria for what belongs to its composition and for what can follow from what has already been composed.</p>
          <p>This interior must possess <em>consistency</em>. Without consistency there can be no sustained composition. But consistency should not be confused with completeness, closure or immunity from change. On the contrary, a discipline that could only preserve its existing consistency would be incapable of producing anything beyond the possibilities already available to it. The decisive question is what happens when the resources through which a discipline has organized itself encounter their own limit.</p>
          <p>Such limits take the form of <em>impasses</em>. An impasse marks a point at which a discipline cannot decide, discern or otherwise resolve something with the resources presently available to it. An impasse is therefore internal to a consistency: it marks an insufficiency in the existing resources of thought.</p>
          <p>An impasse should not, however, be confused with what I call <em>excess</em>. Excess belongs to a different register. It names the more fundamental relation expressed by what I call the <em>axiom of materialism: being exceeds thinking</em>. Thinking is a region of being and cannot exhaust it. Excess names this irreducibility of being to its capture by thought.</p>
          <p>The distinction between impasse and excess is crucial because an impasse alone can become the occasion for a new disciplinary construction without thereby producing a truth. A discipline can confront something undecidable or indiscernible according to its existing resources, make a decision, and construct the consequences of that decision. Through such a procedure it can extend itself and produce a consistency that was not previously available within its interior. Such a consistency can acquire universality without thereby possessing the stronger status that I associate with truth.</p>
          <p>Truth requires something more. It requires an impasse encountered <em>in the presence of the excess of being over thought</em>. Here disciplinary composition does not merely construct beyond an insufficiency in its existing resources. Through that impasse it comes into relation with something of being that those resources could not capture. If the consequences of this encounter can be composed and sustained, what results is not merely another consistency produced through disciplinary extension but what I call an <em>invariant consistency</em>. This is the stronger condition under which I speak of truth and, ultimately, of absoluteness.</p>
          <p>The Theory of Discipline belongs to a quadripartite architecture that is fundamental to my work: <em>mathematics, ontology, philosophy,</em> and <em>discipline</em>. The distinction among these four registers is especially important here because the possibility of truth cannot be accounted for by the logic of disciplinary composition alone. Mathematics supplies formal resources through which consistency, infinity, impasse, extension and invariance can be thought. Ontology concerns being as being. Philosophy articulates, among other things, the materialist relation between being and thought expressed by the axiom that being exceeds thinking. The Theory of Discipline concerns the logic of composition. None of these registers can simply substitute for the others. Truth becomes thinkable through their articulation: disciplinary composition provides the machinery, while the excess of being over thought provides the material condition under which that machinery can become truth-producing.</p>
          <p>This distinction also helps clarify the scope of the Theory of Discipline. <em>Composition is more general than truth.</em> The same disciplinary operations can construct consistencies without every such construction being a truth. This is important because discipline is not a special procedure activated only on exceptional occasions. It is a general logic of thought capable of different kinds of composition. Truth names one of its strongest possibilities.</p>
          <p>The technical architecture of the Theory of Discipline describes the conditions and operations involved in this life of composition. I distinguish between constitutive features—such as beginning, interiority, consistency and novelty—and operative features such as maximality, genericity, subjectivity, locality and universality. These terms have precise meanings in my more systematic work, but their common purpose can be stated simply: they concern how a composition can be extended to the limits of what it is capable of sustaining; how it can admit what could not be identified through its previous classifications; how the consequences of that admission are constructed and maintained; and how what begins locally can acquire a significance that is not confined to the circumstances of its beginning.</p>
          <p>A discipline is therefore neither a fixed structure nor simply a procedure governed by rules. It has a <em>life</em>. It begins, constructs an interior, develops a consistency, encounters impasses and, when conditions permit, composes consequences through them. The resulting composition can transform the discipline itself. And under the stronger material condition in which the impasse is encountered in the presence of excess, disciplinary composition can participate in the production of truth.</p>
          <p>This is also the context for one of the more unusual claims of the Theory of Discipline: <em>the subject is the discipline in composition</em>.</p>
          <p>The subject, in this sense, is not first an individual consciousness confronting an object, nor a pre-existing agent who subsequently decides to undertake a procedure. Subjectivity names the active life of the composition itself: the work through which consequences are drawn, tested, maintained and extended. Individuals participate in this work, sometimes decisively, but the consistency being composed exceeds any one of them. A mathematical truth, a political sequence, an artistic creation or a love cannot be reduced to the biography or intentions of the individuals through whom it takes place.</p>
          <p>This is why the Theory of Discipline is not principally a theory of knowledge. Its central question is not how a subject can obtain an accurate representation of an independently existing object. Its concern is <em>composition</em> and, in its strongest form, <em>truth as composition under a material condition</em>. It asks how thought, situated within being and without recourse to a transcendent guarantee, can compose a consistency that was not already available within its existing resources.</p>
          <p>We can now see more precisely the relation between discipline, truth and novelty. Discipline provides the logic of composition. Truth names an invariant consistency composed where disciplinary thought encounters an impasse in the presence of the excess of being over thought. <em>Novelty is a consequence of truth</em>: the appearance, within a situated discipline, of a consistency that its previous resources could not derive.</p>
          <p>This gives a first answer to the question from which I began: <em>How is novelty possible?</em></p>
          <p>It does not require an intervention from outside being, nor is it simply the unfolding of possibilities already contained within thought. Being exceeds thought; a discipline encounters this excess through a situated impasse; and disciplinary composition can, under certain conditions, construct and sustain the consequences of that encounter.</p>
          <p>The Theory of Discipline is an attempt to understand how this is possible.</p>
        </EssaySection>

        <EssaySection id="part-IV" title="Discipline as a Method of Thinking">
          <p>If discipline names the logic through which a new consistency can be composed, its significance cannot be confined to a theory of truth or to an interpretation of Badiou. It raises a more general question: <em>what kind of thinking is disciplinary thinking?</em></p>
          <p>I have increasingly come to see an old Platonic problem behind this question. Plato distinguishes between different modes of thought according to their relation to their beginnings. At the highest level, dialectic does not simply accept its hypotheses but seeks to move beyond them toward a principle that is no longer hypothetical, in relation to <em>nous</em>. Mathematical thought occupies a different position. It begins from hypotheses that it does not itself ground and proceeds rigorously from them. Below these forms of thought lies <em>doxa</em>, opinion, whose relation to what appears lacks the constructive rigor of axiomatic thinking.</p>
          <p>Whatever we make of Plato’s hierarchy today, the distinction identifies a fundamental problem. <em>How does thought proceed when it has no access to an ultimate principle capable of guaranteeing its beginning?</em></p>
          <p>For philosophy after the disappearance of transcendence, this is no longer a secondary condition. We cannot assume a position outside being from which the correctness of our beginnings can finally be certified. Thought must begin without possessing an absolute justification for its beginning, and yet the consequences of that beginning need not therefore be arbitrary. It can proceed axiomatically: deciding its beginnings, constructing their consequences and submitting those constructions to requirements of consistency.</p>
          <p>The Theory of Discipline belongs to this space. But discipline cannot be reduced simply to axiomatics. Axiomatic beginning explains how a disciplined composition can start without an ultimate ground; it does not by itself explain the entire life of that composition. A discipline must also be capable of reaching the limits of its established consistency, encountering what its existing resources cannot capture, and constructing consequences through that encounter. This requires operations that become visible only much later in the history of thought.</p>
          <p>Modern mathematics is decisive here. It provides much more than a model of deductive rigor. Its development has produced ways of thinking maximality, genericity, locality, different orders of infinity, undecidability, extension and invariance. These are not merely technical mathematical notions that philosophy can borrow as metaphors. They reveal possibilities of thought: ways in which a consistency can be constructed, extended, encounter its own limits, and nevertheless continue.</p>
          <p>This is one reason Badiou is so important to the development of the Theory of Discipline. Few contemporary philosophers have taken the philosophical consequences of modern mathematics as seriously. Across his work, concepts and operations derived from mathematics become indispensable to thinking being, event, truth, subjectivity and the absolute. Yet these operations remain distributed across different stages and problems of his philosophy. Badiou does not gather them together as elements of a general logic of disciplinary thought.</p>
          <p>The Theory of Discipline proposes that they can be understood in precisely this way.</p>
          <p>This also allows me to reconsider the relation between discipline and <em>dialectic</em>. What is today called dialectical thinking is obviously not identical to Plato’s dialectic. In its modern forms, dialectic describes particular ways in which thought proceeds through contradiction, negation, transformation and the production of new determinations. I have argued that, understood in this sense, dialectic is not the most general form of thought. It is a <em>regionalization of the logic of discipline</em>: one powerful way in which disciplinary composition can proceed, but not the form that every composition must take.</p>
          <p>Discipline is more general because contradiction is not the only form in which a consistency encounters its limit. An impasse can take the form of undecidability, indiscernibility, incompleteness, incompatibility with an established classification, or other forms in which the resources of an established consistency no longer suffice. What matters at the more general level is the capacity of a composition to encounter such a point and to make that insufficiency productive.</p>
          <p>This is the larger philosophical claim toward which the Theory of Discipline has gradually led me. Plato recognized the extraordinary status of thought that can proceed rigorously from beginnings it does not ultimately ground. Modern mathematics has enormously expanded our understanding of what such thinking can do. Badiou brought many of these resources into philosophy and demonstrated their power for thinking truth and novelty. The Theory of Discipline attempts to gather the operations involved into a coherent logic.</p>
          <p>In this sense, discipline may name something that remained <em>unthought not only in Badiou but, in a different sense, in the Platonic inheritance itself</em>. This does not mean that Plato possessed an undeveloped Theory of Discipline, or that two millennia of philosophy can be retrospectively assimilated to it. It means that a form of thinking whose philosophical place was recognized very early has acquired operations and capacities that could not have been articulated in its ancient formulation.</p>
          <p>To make discipline explicit as a method of thinking is therefore not to complete that history. It is to recognize that we may only now be in a position to ask systematically what this form of thought is capable of.</p>
        </EssaySection>

        <EssaySection id="part-V" title="Discipline, Truth, and Novelty">
          <p>The Theory of Discipline began for me with the problem of novelty, but its development increasingly brought that problem into relation with <em>truth</em>. Looking back, I have come to organize this relation through three questions that were not themselves the original architecture of my work:</p>
          <p><em>What is a truth?</em><br /><em>How is a truth possible?</em><br /><em>Where is a truth possible?</em></p>
          <p>The first question is ancient. The second acquires a particular urgency with modernity and becomes unavoidable once truth can no longer appeal to a transcendent source or guarantee. The third arises more specifically from the architecture of the Theory of Discipline. Badiou had already made a decisive move in this direction by insisting that philosophy does not itself produce truths: truths are produced in determinate procedures—science, politics, art and love. The Theory of Discipline allows the question of their site to be posed more generally. If a truth must be composed, what kind of site is capable of sustaining that composition? My answer is: <em>a truth is possible in a discipline</em>.</p>
          <p>This does not mean that truth is true only relative to the discipline in which it is produced. The distinction between the <em>site of composition</em> and the <em>scope of truth</em> is essential. A truth has to begin locally, under particular conditions and through particular procedures. But if its validity were permanently confined to those conditions, it would remain a local construction rather than a truth. One of the problems addressed by the Theory of Discipline is precisely how something composed from a determinate beginning can acquire a significance that is not confined to the circumstances of its production.</p>
          <p>In my second book, I express the compositional being of a truth through a triad:</p>
          <p><em>Truth = Idea + Generic + Fidelity</em></p>
          <p>The three terms do not designate three things that, when combined, constitute truth. They name three functions within a single composition.</p>
          <p>An <em>Idea</em> provides orientation. A discipline does not construct blindly. An Idea organizes what is to be done and makes intelligible why certain constructions and consequences matter.</p>
          <p>The <em>generic</em> concerns the relation of the composition to what the established interior could not previously discern. If everything admitted into a discipline were already identifiable according to its existing classifications, the composition would remain confined to those classifications. Genericity makes possible a construction that is not reducible to these prior determinations.</p>
          <p><em>Fidelity</em> names the work through which the consequences of the composition are sustained. A truth does not exist simply because an encounter occurs. Its consequences have to be drawn, maintained and extended. Fidelity is this continuing labour of composition.</p>
          <p>The triad can therefore be understood as <em>orientation, construction and continuation</em>. Together they describe the compositional life through which a truth acquires consistency. But they do not, by themselves, distinguish the composition of a truth from every other disciplinary composition. The distinction introduced earlier is indispensable here. The triad describes the <em>compositional form</em> of truth; truth also has a <em>material condition</em>. That condition is supplied when disciplinary thought encounters an impasse in the presence of the excess of being over thought.</p>
          <p>This is why, elsewhere in my work, particularly when the question shifts from the composition of truth to its material status, I describe truth as an <em>invariant consistency</em>. Invariance does not simply mean that a truth lasts for a long time or survives changes in historical circumstances. It concerns the relation of the composed consistency to being. Where composition captures consequences of an encounter with what exceeded the previous resources of thought, the resulting consistency cannot be reduced to the particular resources through which it was composed.</p>
          <p>The two formulations therefore approach truth from different but complementary directions. <em>Idea + Generic + Fidelity</em> describes its compositional life: orientation, construction and continuation. <em>Invariant consistency</em> identifies the stronger status of a composition produced under the material condition of excess. The first tells us how truth is composed; the second helps explain why the resulting consistency is not exhausted by the situated conditions of its composition.</p>
          <p>This distinction also clarifies the relation between <em>universality</em> and <em>absoluteness</em>. Disciplinary composition can produce a consistency whose consequences extend beyond the locality of its beginning and thereby acquire universality. But universality alone does not establish truth. Where composition occurs under the material condition of excess, the resulting invariant consistency acquires the stronger status that I associate with absoluteness. Truth is therefore not simply whatever successfully extends beyond its initial locality.</p>
          <p>We can now return to the question with which this account began: <em>how is novelty possible?</em></p>
          <p>Truth and novelty should not be identified. Novelty is not the definition of truth, nor does every disciplinary construction produce novelty. As we have seen, a discipline can construct beyond an impasse and produce a consistency not previously available within its interior without thereby producing a truth. Novelty, in the sense established at the beginning of this essay, belongs to the stronger case.</p>
          <p><em>Novelty is a consequence of truth.</em> Where a truth is composed, an invariant consistency comes to exist that could not be derived from the previous resources of the situated discipline. From within that situation, something has become possible that its established resources could neither derive nor anticipate.</p>
          <p>There is an important asymmetry here. My philosophical path approached truth through the problem of novelty: <em>how can something radically new come to exist?</em> But the Theory of Discipline eventually reverses the explanatory direction. Once truth is understood as a disciplined composition under a material condition, it is truth that allows us to understand how novelty is possible.</p>
          <p><em>We arrive at truth through the problem of novelty; we return from truth with an account of the possibility of novelty.</em></p>
          <p>This relation is one reason I regard discipline as central. Truth does not occur in an abstract space. Its composition has a life: it requires orientation, construction and continuation; it begins within a situated interior; and its consequences have to be sustained. Discipline is not simply the environment in which a truth happens to occur. It is the form through which a truth can be composed.</p>
          <p>The question <em>where is truth possible?</em> consequently leads back to the central claim of the Theory of Discipline. Truth is possible where a situated composition can encounter an impasse in the presence of what exceeds its existing resources and sustain the consequences of that encounter.</p>
          <p>It is possible <em>in the life of a discipline</em>.</p>
        </EssaySection>

        <EssaySection id="part-VI" title="Why Do We Need Truth?">
          <p>The development of the Theory of Discipline has given me a way of approaching three questions: <em>what is a truth, how is a truth possible,</em> and <em>where is a truth possible?</em> But there is a fourth question that the theory, by itself, does not answer:</p>
          <p><em>Why do we need truth?</em></p>
          <p>The distinction between the third and fourth questions is important. To show how truth can be composed without transcendence is to establish a possibility. It does not yet establish why that possibility should matter to us, or why philosophy should take it as one of its central concerns. <em>Possibility is not necessity.</em></p>
          <p>This is where my current work begins.</p>
          <p>Looking at the contemporary world, what strikes me first is not an explicit crisis of truth. Truth is not something we ordinarily encounter as such in everyday experience. What we encounter more immediately is a profound difficulty in thinking novelty.</p>
          <p>Our time is hardly lacking in change. Technological transformation is relentless. Political arrangements shift, new cultural forms appear, social relations are reorganized, and possibilities that seemed remote can become ordinary with remarkable speed. We are also capable of imagining catastrophe with considerable ease. Yet this abundance of change coexists with a peculiar inability to imagine the production of a consistency whose possibilities are not already measured by the coordinates of the world in which it appears.</p>
          <p>The problem is therefore not that nothing changes. It is that change increasingly takes place against a horizon that itself appears immovable.</p>
          <p>This is why the contemporary problem of truth first presents itself to me as a <em>crisis of novelty</em>. We encounter the repetition of established alternatives, the naturalization of arrangements that are historically contingent, and the tendency to treat the limits of the present as though they were limits of possibility itself. Novelty becomes difficult not merely to produce but even to think.</p>
          <p>The relation developed by the Theory of Discipline gives this diagnosis a particular significance. If novelty is a consequence of truth, then the foreclosure of novelty is not merely a failure of imagination. It points toward a deeper problem concerning the conditions under which truths can acquire a life.</p>
          <p>This is the point of departure of my current project, <em>Philosophy and the Theory of Discipline</em>. Its initial task is therefore diagnostic. Why has novelty become so difficult to think? What features of contemporary thought encourage us to naturalize the present? And what does this tell us about the philosophical categories through which we understand possibility?</p>
          <p>One of the claims I am exploring is that <em>novelty should occupy a central place in philosophy</em>. This does not mean replacing truth with novelty. The Theory of Discipline gives me every reason to insist upon their distinction: truth is an invariant consistency composed under a material condition; novelty is one of its consequences. The claim concerns instead the organization of philosophical inquiry. Novelty is where the problem of truth becomes perceptible to us. It is through the question of whether novelty is possible that we are led back to the conditions of truth.</p>
          <p>This also changes the place of the <em>subject</em>. Much modern and contemporary philosophy has made the subject one of its organizing categories. The Theory of Discipline does not eliminate subjectivity; it relocates it. If the subject is the discipline in composition, then subjectivity belongs within the larger problem of how a consistency is produced and sustained. The subject becomes one moment in the life of truth rather than the category around which the entire philosophical field must be organized.</p>
          <p>But the diagnosis of the present and the reorganization of philosophy around the problem of novelty constitute only the beginning of the project. The larger question is what follows if discipline is taken seriously as a method of thinking.</p>
          <p>My first book encountered discipline while trying to understand Badiou’s philosophy of subjectivity and infinity. My second developed it systematically in relation to <em>The Immanence of Truths</em> and the problem of the composition and absoluteness of truth. The work I am undertaking now asks what happens when the Theory of Discipline is brought back into philosophy not merely as a way of interpreting Badiou, nor solely as an account of how truths are possible, but as a conscious method of thought in its own right.</p>
          <p>In that sense, the fourth question—<em>why do we need truth?</em>—does more than add another problem to the first three. It asks why the possibilities disclosed by the Theory of Discipline should matter under the conditions of our present, and what philosophy becomes if it accepts those possibilities as consequential.</p>
          <p>I began by asking <em>how is the new possible?</em> The Theory of Discipline has given that question a more precise form: <em>how is novelty possible?</em> Its answer is that novelty becomes possible through the composition of truth: through the capacity of situated disciplinary thought to encounter an impasse in the presence of what exceeds it and to compose and sustain the consequences of that encounter.</p>
          <p>The question I am pursuing now is what we are prepared to do with that possibility.</p>
        </EssaySection>
      </main>
      <SiteFooter />
    </>
  );
}
