export default function DarkEnlightenmentPartOneSectionGroup2() {
  return (
    <>
      <section id="ontology">
        <h2>4. Ontology: Contradiction vs Generativity</h2>
        <p>The distinction we have just introduced can be clarified at a more fundamental level. It is not simply a difference in how capitalism is interpreted, but a difference in how transformation itself is understood. In other words, it is an ontological difference.</p>
        <p>Both Georg Wilhelm Friedrich Hegel and Baruch Spinoza are thinkers of immanence. In both cases, change does not come from an external force imposed upon reality, but unfolds from within it. However, the principle that drives this immanent transformation is not the same.</p>
        <p>In the Hegelian lineage taken up by Karl Marx, transformation is structured by contradiction. Social and historical forms are not stable wholes, but internally divided. These divisions generate tensions that cannot be resolved within the existing configuration, and it is this inability that drives change. Transformation, in this sense, is not simply movement, but the result of a process in which a form encounters its own limits and is forced beyond them.</p>
        <p>This is why contradiction is not merely a descriptive feature of capitalism, but a structural one. It explains both how the system operates and why it is unstable. At the same time, as we have seen, this instability does not resolve itself automatically. The tensions of the system must be articulated and organized through political mediation in order to produce transformation.</p>
        <p>A simple example from Marx’s Capital helps clarify this. One of the fundamental tensions he identifies is the distinction between use-value and exchange-value. Every commodity has a use—it satisfies a need—but in capitalism it is produced and circulated primarily as an object of exchange, that is, as something that realizes value in the market. These two dimensions do not coincide. What is useful is not necessarily what is profitable, and what is profitable is not necessarily what is socially necessary. This tension is constitutive of the system, and it appears in concrete forms—overproduction alongside unmet needs, the destruction of goods in the face of scarcity, and the prioritization of profit over utility. It is in this sense that contradiction both sustains the system and points toward its limits.</p>
        <p>In the Spinozist lineage taken up by Gilles Deleuze, the situation is different. Transformation is not grounded in contradiction, but in the productive capacity of being itself. Reality is not primarily understood as divided against itself, but as composed of processes that continuously generate new forms and relations. Change does not arise from the failure of a system to maintain itself, but from its capacity to produce variation.</p>
        <p>From this perspective, what we call a “system” is not a unified structure containing internal opposition, but a configuration of relations that can be reconfigured in multiple ways. Transformation does not require breakdown or crisis in the Hegelian sense. It can occur through shifts, recompositions, and reorientations within the field itself.</p>
        <p>A simple example, drawn from Spinoza’s way of thinking, helps clarify this. Consider a body—not as a fixed object, but as a composition of relations between its parts: motions, speeds, and interactions. What the body is depends on how these relations are organized. If these relations change—if they are recomposed—the body itself changes. This transformation does not require contradiction within the body. It occurs through a reconfiguration of its elements. The same components can enter into different compositions, producing different forms and capacities.</p>
        <p>The difference, then, is not between change and stability, but between two models of change. In one case, transformation is driven by internal tension and its limits. In the other, it is driven by generativity and the possibilities it opens.</p>
        <p>This difference has important consequences for how capitalism is understood. In the Marxist framework, capitalism contains the conditions of its own transformation in the form of structural tensions that point beyond it. In the Deleuzian framework, capitalism is a configuration that operates within a broader field of generative processes, reorganizing and redirecting them without necessarily leading to a determinate outcome.</p>
        <p>It is this shift—from contradiction as the motor of transformation to generativity as its condition—that marks the ontological divergence between these two approaches.</p>
      </section>

      <section id="subject-agency">
        <h2>5. Subject and Agency</h2>
        <p>The ontological difference we have just outlined is accompanied by a corresponding difference in the theory of the subject.</p>
        <p>In the Marxist framework, transformation does not occur automatically. Although capitalism is structured by internal tensions, these do not resolve themselves on their own. They create the conditions for change, but they do not complete the process. For transformation to occur, these conditions must be taken up, articulated, and organized through collective action. This is the role of the subject.</p>
        <p>The proletariat, in this context, is not simply a sociological category. It designates the point at which the tensions of the system become capable of being recognized and acted upon. Political practice is therefore essential. Through organization, strategy, and intervention, these tensions are transformed into forces capable of producing change. In this sense, the subject is immanent to the process, but it occupies a privileged position within it: it is the site at which transformation becomes effective.</p>
        <p>In the Deleuzian framework, this role is fundamentally reconfigured. The difference is not that the subject is outside the system in one case and inside it in the other—both frameworks are immanent. The difference lies in the role the subject plays.</p>
        <p>In the Marxist framework, the subject is structurally necessary. Without the organization of a collective subject, transformation does not occur. In the Deleuzian framework, this privilege disappears. The subject is no longer the site at which transformation is concentrated or organized. It becomes one element among others within a field of processes.</p>
        <p>Change, from this perspective, does not depend on the formation of a unified subject, but on shifts in the configuration of relations that constitute the system itself. What we call “agency” is not the expression of a subject directing the process, but a local modification within it.</p>
        <p>This leads to a different conception of politics.</p>
        <p>In the Marxist framework, politics is inseparable from the organization of a subject capable of giving form to the tensions of the system. Without such organization, transformation cannot take place.</p>
        <p>In the Deleuzian framework, by contrast, organization becomes contingent rather than necessary. Processes continue to operate and transform regardless of whether they are unified into a subject or directed toward a common end. Political action is therefore no longer the construction of a subject that directs history, but a local intervention within ongoing processes—an attempt to reconfigure relations that may or may not stabilize into a larger structure.</p>
        <p>Politics, in this sense, becomes experimental. It does not guarantee a trajectory from present conditions to a determinate future. It operates within a field where the generation of relations exceeds any stable form of organization.</p>
        <p>The difference, then, is not simply that one framework emphasizes the subject and the other does not. It is that in one case, transformation depends on the successful organization of processes into a coherent form, while in the other, processes continue to generate change even in the absence of such organization.</p>
      </section>

      <section id="crisis-of-mediation">
        <h2>6. Historical Transformation: Crisis of Mediation</h2>
        <p>The shift we have been describing should not be understood as a purely philosophical development. It is rooted in a broader historical transformation that affects the conditions under which political action takes place.</p>
        <p>By the mid-twentieth century, the forms through which Marxist theory had been translated into practice—political parties, labor movements, and revolutionary organizations—began to lose much of their effectiveness. These forms were designed to mediate between structural conditions and political transformation: to organize the tensions of capitalism into a collective force capable of producing change.</p>
        <p>However, the historical situation in which they operated had changed.</p>
        <p>In Western societies, capitalism did not collapse under the weight of these tensions. Instead, it stabilized and expanded. Economic growth, the development of welfare institutions, and the integration of large segments of the working class into systems of consumption and social security altered the conditions under which political conflict had previously been understood. The figure of the proletariat as a unified and revolutionary subject became increasingly difficult to sustain in practice.</p>
        <p>At the same time, attempts at revolutionary transformation elsewhere did not produce the expected outcomes. The Soviet model became associated with bureaucratic rigidity rather than emancipatory transformation, and other movements struggled to establish durable alternatives. The expectation that structural tensions would lead, through political mediation, to a new social order was no longer confirmed by historical experience.</p>
        <p>The events of May ’68 in France crystallized these tensions. While often remembered as a moment of radical possibility, its aftermath revealed the difficulty of translating widespread social unrest into lasting political transformation. The energy of the moment did not consolidate into a new form of organization, but was rapidly reabsorbed into the existing system.</p>
        <p>What emerges from this situation is not the disappearance of tension, but a growing uncertainty about the mechanisms through which it can be made effective. The problem is no longer simply that capitalism contains internal divisions, but that these divisions do not produce the kind of transformation that had been anticipated.</p>
        <p>In other words, what enters into crisis is not Marx’s analysis of capitalism, but the political mediation of that analysis. The link between structural tension and organized transformation becomes unstable.</p>
        <p>This raises a new question:</p>
        <p>If transformation does not reliably follow from these conditions through the organization of a subject, how are we to understand a system that continues to function, adapt, and reorganize itself without producing the rupture it was expected to generate?</p>
        <p>It is this question that opens the way for the theoretical shifts we will examine next.</p>
      </section>

      <section id="critique-to-process">
        <h2>7. From Critique to Process</h2>
        <p>In response to this historical situation, a shift begins to take shape. It is important to emphasize that this shift does not arise from a rejection of Marx’s analysis. The problem is not that capitalism ceases to be intelligible in Marxist terms, but that the mechanisms through which this analysis was expected to become effective—through political mediation and the organization of a subject—no longer appear reliable.</p>
        <p>What changes, therefore, is not the desire to understand capitalism, but the framework within which that understanding takes place.</p>
        <p>In the classical Marxist model, critique is oriented toward identifying internal tensions and organizing them into a force capable of producing transformation. It is inseparable from a trajectory: it points beyond the present toward a determinate form of change.</p>
        <p>In the emerging framework, this orientation becomes difficult to sustain. If these tensions do not reliably produce transformation, and if political mediation fails to organize them into an effective force, then the focus of analysis begins to shift. Rather than asking how the system might be overcome, attention turns to how it operates.</p>
        <p>This does not mean abandoning critique, but relocating it.</p>
        <p>Capitalism is no longer approached primarily as a system whose internal tensions must be resolved, but as one that functions through ongoing processes—processes that produce, reproduce, and reorganize themselves. The emphasis shifts:</p>
        <p className="seminar-bullet">from conflict to functioning • from opposition to production • from subjective action to systemic process</p>
        <p>Social reality is no longer understood as something that awaits intervention in order to be transformed. It is understood as already active—already producing effects, adapting, and reorganizing itself. The question is no longer how to initiate change from the outside, but how to understand the dynamics through which the system maintains and modifies itself from within.</p>
        <p>This shift extends beyond Marxist theory. It reflects a broader transformation in how social reality is approached, one in which the centrality of the subject becomes increasingly difficult to sustain.</p>
        <p>At this stage, however, the shift remains largely implicit. It appears as a displacement in orientation rather than a fully articulated framework.</p>
        <p>It is only in the next stage that this shift takes a more explicit conceptual form.</p>
      </section>
    </>
  );
}
